### ISSUE TITLE
why I can't open the project?

### ISSUE THREAD

**Issue by yangyongwff** [DanWatkins/Terrain3D#6]
thank you, I am interested in your project, but when I run the  project, it has something mistakes that i don't 
know how to solve them. When i open the Terrain3D.qbs, it looks like that 
![360 20171026204145403](https://user-images.githubusercontent.com/22364186/32054170-1f99c4a8-ba90-11e7-8490-da247e4ff235.jpg)

why App.qbs, Src.qbs, Tests.qbs is gray?  they all exits in the local path, could you give me a hand.

**Comment by DanWatkins** [comment]
Are there any errors/warnings displayed in the issues panel? If you ended up getting it to work, what was the solution?

**Comment by yangyongwff** [comment]
When I use Qt Creator to open the project，then Configure project. Only when i choose the Mingw
it can work. Other options such as MSVC 2015 and MSVC 2013 can't work. 
Besides, the working directory is set to <root_path_to_terrain3d>/Deployment/ instead of Deployment/Bin/, Because when I download the project, Resourse is under the Deployment folder.
![360 20171102105323269](https://user-images.githubusercontent.com/22364186/32307595-337ca5e0-bfbc-11e7-8bda-0989e55094b4.jpg)

**Comment by DanWatkins** [comment]
Do you have the Visual C++ Build Tools (2013, 2015, 2017) installed for the MSVC version you are trying to configure?

http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by yangyongwff** [comment]
yes, you are right. The program has been executived correctly. thank you! haha

-

**Comment by DyncKevin** [comment]
hi, i got same problem. but I am using Mac OS 10.13.1, QtCreator 4.10.2 based on Qt 5.13.2
 the  App.qbs, Src.qbs, Tests.qbs are gray, how should I config the setting ?

**Comment by DanWatkins** [comment]
Hi @DyncKevin, thanks for trying this on a Mac. It's been years since I had one to test this on. Do you get any errors or warnings in any of the panes at the bottom of Qt Creator? Specifically the "General Messages" pane. It might be hidden by default.

![image](https://user-images.githubusercontent.com/1879175/75744872-39784d00-5cdb-11ea-885f-d95a7c24b473.png)

The readme states OpenGL 4.3 is required, but I did demote a lot to just use just 4.1 to try and get it working on Mac OS. Apple never added OpenGL support after 4.1 except for several extensions from 4.2. This should not effect your ability to load it in Qt Creator.

Somewhat related: I just tried building the project on Windows with Qt 5.14 and it appears there is a build error with the GLM dependency using the newer version of GCC shipped with Qt on Windows (#7). This likely is not an issue on Mac however if you are using Clang.
